'use strict';

/**
 * Framed-JSON IPC over localhost TCP — the transport between the Bridge
 * (hub side) and each Channel server (client side, spawned by Claude Code).
 *
 * Wire format: one JSON object per line ("\n"-terminated, UTF-8). A line is
 * at most MAX_FRAME_BYTES; oversized lines kill the connection (bounded
 * payloads). Heartbeat pings keep liveness; a silent peer for
 * HEARTBEAT_INTERVAL_MS * 3 is considered dead.
 *
 * Security: connections are authenticated with a per-hub random secret the
 * client must present in its `hello` frame. The server binds 127.0.0.1 ONLY
 * (never 0.0.0.0). The secret is generated by the Bridge, never the bot
 * token or any API credential.
 *
 * Both sides use the same tiny protocol; createIpcServer/createIpcClient
 * wrap net.Server/net.Socket with identical framing.
 */

const net = require('net');

const MAX_FRAME_BYTES = 512 * 1024; // 512 KiB per frame — messages are text, files go by path
const HEARTBEAT_INTERVAL_MS = 5000;
const HEARTBEAT_TIMEOUT_MS = HEARTBEAT_INTERVAL_MS * 3;

/** Attach line-framing + JSON to a socket. Returns { send, close, on }. */
function attachFraming(socket, { onError = () => {} } = {}) {
  const listeners = { message: [], close: [], error: [] };
  let buf = '';
  let closed = false;

  socket.setEncoding('utf8');
  socket.on('data', (chunk) => {
    buf += chunk;
    if (buf.length > MAX_FRAME_BYTES) {
      onError(new Error('frame too large')); // unbounded payload attempt
      socket.destroy();
      return;
    }
    let idx;
    while ((idx = buf.indexOf('\n')) !== -1) {
      const line = buf.slice(0, idx);
      buf = buf.slice(idx + 1);
      if (!line.trim()) continue;
      let msg = null;
      try {
        msg = JSON.parse(line);
      } catch (err) {
        onError(new Error(`bad frame: ${err.message}`));
        socket.destroy();
        return;
      }
      for (const fn of listeners.message) fn(msg);
    }
  });
  socket.on('close', () => {
    if (closed) return;
    closed = true;
    for (const fn of listeners.close) fn();
  });
  socket.on('error', (err) => {
    for (const fn of listeners.error) fn(err);
    onError(err);
  });

  return {
    send(obj) {
      if (closed || socket.destroyed) return false;
      let line;
      try {
        line = JSON.stringify(obj);
      } catch (err) {
        onError(err);
        return false;
      }
      if (Buffer.byteLength(line, 'utf8') > MAX_FRAME_BYTES) {
        onError(new Error('outgoing frame too large'));
        return false;
      }
      socket.write(line + '\n');
      return true;
    },
    close() {
      try {
        socket.end();
      } catch {
        /* ignore */
      }
    },
    destroy() {
      closed = true;
      try {
        socket.destroy();
      } catch {
        /* ignore */
      }
    },
    on(event, fn) {
      if (listeners[event]) listeners[event].push(fn);
      return () => {
        const i = listeners[event].indexOf(fn);
        if (i !== -1) listeners[event].splice(i, 1);
      };
    },
    get remoteAddress() {
      return socket.remoteAddress;
    },
  };
}

/**
 * Hub (Bridge) side. Listens on 127.0.0.1:<port> (or an ephemeral port when
 * port is 0). Each connection must send {type:'hello', secret, ...} within
 * HELLO_TIMEOUT_MS or is destroyed. After a valid hello, `onConnection`
 * receives { conn, hello, reply } where reply(msg) is a helper that tags
 * responses to this connection.
 */
function createIpcServer({ port = 0, secret, logInfo = () => {}, logWarn = () => {} } = {}) {
  const HELLO_TIMEOUT_MS = 10_000;
  const conns = new Set();
  let heartbeatTimer = null;

  const server = net.createServer((raw) => {
    // Enforce loopback at the socket level too (defense in depth).
    const addr = raw.remoteAddress || '';
    if (!/^(127\.|::1|::ffff:127\.)/.test(addr)) {
      logWarn(`ipc: rejected non-loopback connection from ${addr}`);
      raw.destroy();
      return;
    }
    const conn = attachFraming(raw, {
      onError: (err) => logWarn(`ipc client error ${addr}: ${err.message}`),
    });
    conn.helloDone = false;
    conns.add(conn);

    const helloTimer = setTimeout(() => {
      if (!conn.helloDone) {
        logWarn('ipc: client did not authenticate in time');
        conn.destroy();
      }
    }, HELLO_TIMEOUT_MS);
    if (helloTimer.unref) helloTimer.unref();

    const offMsg = conn.on('message', (msg) => {
      if (!conn.helloDone) {
        if (!msg || msg.type !== 'hello' || typeof msg.secret !== 'string' || msg.secret.length < 16) {
          logWarn('ipc: invalid or missing hello/secret — connection rejected');
          conn.destroy();
          return;
        }
        // constant-time-ish compare
        const a = Buffer.from(msg.secret);
        const b = Buffer.from(secret);
        if (a.length !== b.length || !require('crypto').timingSafeEqual(a, b)) {
          logWarn('ipc: bad secret — connection rejected');
          conn.destroy();
          return;
        }
        conn.helloDone = true;
        clearTimeout(helloTimer);
        conn.send({ type: 'hello_ok', protocol: 1 });
        onConnection({ conn, hello: msg });
        return;
      }
      if (msg.type === 'ping') {
        conn.send({ type: 'pong', t: msg.t });
      }
      // everything else is routed by the hub's onConnection handler
    });
    conn.on('close', () => {
      conns.delete(conn);
      clearTimeout(helloTimer);
      offMsg();
    });
  });

  server.on('error', (err) => logWarn(`ipc server error: ${err.message}`));

  function startHeartbeats() {
    heartbeatTimer = setInterval(() => {
      for (const c of conns) {
        if (!c.helloDone) continue;
        // If the peer went silent, drop it (close fires; reconnect handles the rest).
        if (c.lastSeen && Date.now() - c.lastSeen > HEARTBEAT_TIMEOUT_MS) {
          c.destroy();
          continue;
        }
        c.send({ type: 'ping', t: Date.now() });
      }
    }, HEARTBEAT_INTERVAL_MS);
    if (heartbeatTimer.unref) heartbeatTimer.unref();
  }

  return {
    listen(cb) {
      server.listen(port, '127.0.0.1', () => {
        const actual = server.address();
        startHeartbeats();
        cb({
          port: typeof actual === 'object' ? actual.port : port,
          host: '127.0.0.1',
        });
      });
    },
    close() {
      if (heartbeatTimer) clearInterval(heartbeatTimer);
      for (const c of [...conns]) c.destroy();
      conns.clear();
      try {
        server.close();
      } catch {
        /* ignore */
      }
    },
    connections: () => [...conns],
  };
}

/**
 * Client (Channel server) side. Connects, sends hello with the secret, and
 * invokes onReady({ conn, hub }) once authenticated. Auto-reconnects with
 * backoff until close() is called.
 */
function createIpcClient({ port, secret, clientId, logInfo = () => {}, logWarn = () => {}, reconnectDelayMs = 2000, maxDelayMs = 15000 } = {}) {
  let conn = null;
  let closedByUs = false;
  let attempts = 0;
  let reconnectTimer = null;
  let heartbeatTimer = null;
  let readyCb = null;
  let messageHandler = null;

  function clearHeartbeat() {
    if (heartbeatTimer) {
      clearInterval(heartbeatTimer);
      heartbeatTimer = null;
    }
  }

  function connectOnce() {
    const raw = net.connect(port, '127.0.0.1');
    const c = attachFraming(raw, { onError: (err) => logWarn(`ipc client: ${err.message}`) });

    c.on('close', () => {
      clearHeartbeat();
      conn = null;
      if (closedByUs) return;
      attempts += 1;
      const delay = Math.min(maxDelayMs, reconnectDelayMs * attempts);
      logWarn(`ipc: disconnected from hub; retrying in ${Math.round(delay / 1000)}s`);
      reconnectTimer = setTimeout(connectOnce, delay);
      if (reconnectTimer.unref) reconnectTimer.unref();
    });

    c.on('message', (msg) => {
      c.lastSeen = Date.now();
      if (msg && msg.type === 'ping') {
        c.send({ type: 'pong', t: msg.t });
        return;
      }
      if (msg && msg.type === 'pong') return;
      if (messageHandler) messageHandler(msg, c);
    });

    raw.on('connect', () => {
      attempts = 0;
      c.send({ type: 'hello', secret, clientId, protocol: 1 });
      heartbeatTimer = setInterval(() => c.send({ type: 'ping', t: Date.now() }), HEARTBEAT_INTERVAL_MS);
      if (heartbeatTimer.unref) heartbeatTimer.unref();
    });

    conn = c;
    return c;
  }

  return {
    start(onReady) {
      readyCb = onReady;
      messageHandler = null;
      // The hub answers hello_ok on the same socket; surface readiness then.
      connectOnce();
      // Wrap messageHandler so hello_ok triggers onReady exactly once per connection.
      const orig = (msg, c) => {
        if (msg && msg.type === 'hello_ok') {
          if (readyCb) readyCb({ conn: c });
          return;
        }
        if (messageHandler) messageHandler(msg, c);
      };
      messageHandler = orig;
    },
    onMessage(fn) {
      messageHandler = fn;
    },
    send(obj) {
      return conn ? conn.send(obj) : false;
    },
    isConnected() {
      return !!conn && !conn.destroyed;
    },
    close() {
      closedByUs = true;
      clearHeartbeat();
      if (reconnectTimer) clearTimeout(reconnectTimer);
      if (conn) conn.close();
      conn = null;
    },
  };
}

module.exports = {
  createIpcServer,
  createIpcClient,
  attachFraming,
  MAX_FRAME_BYTES,
  HEARTBEAT_INTERVAL_MS,
  HEARTBEAT_TIMEOUT_MS,
};
