'use strict';

/**
 * Framed-JSON IPC over localhost TCP — the transport between the Bridge
 * (hub side) and each Channel server (client side, spawned by Claude Code).
 *
 * Wire format: one JSON object per line ("\n"-terminated, UTF-8). A line is
 * at most MAX_FRAME_BYTES; oversized lines kill the connection (bounded
 * payloads). Heartbeat pings keep liveness; a silent peer for
 * HEARTBEAT_INTERVAL_MS * 3 is considered dead.
 *
 * Security: connections are authenticated with a per-hub random secret the
 * client must present in its `hello` frame. The server binds 127.0.0.1 ONLY
 * (never 0.0.0.0). The secret is generated by the Bridge, never the bot
 * token or any API credential.
 *
 * Both sides use the same tiny protocol; createIpcServer/createIpcClient
 * wrap net.Server/net.Socket with identical framing.
 */

const net = require('net');

const MAX_FRAME_BYTES = 512 * 1024; // 512 KiB per frame — messages are text, files go by path
const HEARTBEAT_INTERVAL_DEFAULT_MS = 5000;
const HEARTBEAT_TIMEOUT_DEFAULT_MS = HEARTBEAT_INTERVAL_DEFAULT_MS * 3;
/** Sane bounds for the configurable heartbeat values. */
const HEARTBEAT_BOUNDS = {
  minIntervalMs: 1000,
  maxIntervalMs: 60_000,
  minTimeoutMs: 2000,
  maxTimeoutMs: 300_000,
};

/** Attach line-framing + JSON to a socket. Returns { send, close, on }. */
function attachFraming(socket, { onError = () => {} } = {}) {
  const listeners = { message: [], close: [], error: [] };
  let buf = '';
  // Two distinct lifecycle flags (fix: one overloaded boolean meant destroy()
  // suppressed the close notification, leaving consumers thinking the
  // connection was alive).
  let destroyRequested = false; // local destroy() called
  let closeEmitted = false; // close listeners fired (exactly once)
  let lastSeen = Date.now(); // updated on ANY valid traffic (data/frames)

  function emitCloseOnce() {
    if (closeEmitted) return;
    closeEmitted = true;
    for (const fn of listeners.close) fn();
  }

  socket.setEncoding('utf8');
  socket.on('data', (chunk) => {
    lastSeen = Date.now();
    buf += chunk;
    if (buf.length > MAX_FRAME_BYTES) {
      onError(new Error('frame too large')); // unbounded payload attempt
      socket.destroy();
      return;
    }
    let idx;
    while ((idx = buf.indexOf('\n')) !== -1) {
      const line = buf.slice(0, idx);
      buf = buf.slice(idx + 1);
      if (!line.trim()) continue;
      let msg = null;
      try {
        msg = JSON.parse(line);
      } catch (err) {
        onError(new Error(`bad frame: ${err.message}`));
        socket.destroy();
        return;
      }
      for (const fn of listeners.message) fn(msg);
    }
  });
  socket.on('close', () => {
    // Fires on remote close AND after local destroy() — always notify
    // exactly once so consumers reliably mark the connection dead.
    emitCloseOnce();
  });
  socket.on('error', (err) => {
    for (const fn of listeners.error) fn(err);
    onError(err);
  });

  return {
    send(obj) {
      if (closeEmitted || socket.destroyed) return false;
      let line;
      try {
        line = JSON.stringify(obj);
      } catch (err) {
        onError(err);
        return false;
      }
      if (Buffer.byteLength(line, 'utf8') > MAX_FRAME_BYTES) {
        onError(new Error('outgoing frame too large'));
        return false;
      }
      socket.write(line + '\n');
      return true;
    },
    close() {
      try {
        socket.end();
      } catch {
        /* ignore */
      }
    },
    destroy() {
      destroyRequested = true;
      try {
        socket.destroy();
      } catch {
        /* ignore */
      }
      // Net only emits 'close' after 'end'/'error' in some half-open states;
      // guarantee the notification regardless.
      setImmediate(emitCloseOnce);
    },
    get destroyRequested() {
      return destroyRequested;
    },
    get isUsable() {
      return !closeEmitted && !socket.destroyed;
    },
    on(event, fn) {
      if (listeners[event]) listeners[event].push(fn);
      return () => {
        const i = listeners[event].indexOf(fn);
        if (i !== -1) listeners[event].splice(i, 1);
      };
    },
    get remoteAddress() {
      return socket.remoteAddress;
    },
    /** Last time ANY valid traffic (bytes) arrived on this connection. */
    get lastSeen() {
      return lastSeen;
    },
  };
}

/**
 * Validate heartbeat configuration. Returns {ok, intervalMs, timeoutMs, error}.
 * Missing values fall back to the defaults; explicit values are bounds-checked
 * and the timeout must exceed the interval (a peer must get a chance to answer).
 */
function validateHeartbeatConfig(intervalMs, timeoutMs) {
  const hasI = intervalMs !== undefined && intervalMs !== null && intervalMs !== '';
  const hasT = timeoutMs !== undefined && timeoutMs !== null && timeoutMs !== '';
  const i = hasI ? Number(intervalMs) : HEARTBEAT_INTERVAL_DEFAULT_MS;
  const t = hasT ? Number(timeoutMs) : Math.max(HEARTBEAT_TIMEOUT_DEFAULT_MS, (hasI ? Number(intervalMs) : 0) * 3);
  if (!Number.isInteger(i) || i < HEARTBEAT_BOUNDS.minIntervalMs || i > HEARTBEAT_BOUNDS.maxIntervalMs) {
    return { ok: false, intervalMs: null, timeoutMs: null, error: `CLAUDE_CHANNEL_HEARTBEAT_MS must be an integer between ${HEARTBEAT_BOUNDS.minIntervalMs} and ${HEARTBEAT_BOUNDS.maxIntervalMs}` };
  }
  if (!Number.isInteger(t) || t < HEARTBEAT_BOUNDS.minTimeoutMs || t > HEARTBEAT_BOUNDS.maxTimeoutMs) {
    return { ok: false, intervalMs: null, timeoutMs: null, error: `CLAUDE_CHANNEL_HEARTBEAT_TIMEOUT_MS must be an integer between ${HEARTBEAT_BOUNDS.minTimeoutMs} and ${HEARTBEAT_BOUNDS.maxTimeoutMs}` };
  }
  if (t <= i) {
    return { ok: false, intervalMs: null, timeoutMs: null, error: `CLAUDE_CHANNEL_HEARTBEAT_TIMEOUT_MS (${t}) must be greater than CLAUDE_CHANNEL_HEARTBEAT_MS (${i})` };
  }
  return { ok: true, intervalMs: i, timeoutMs: t, error: null };
}

/**
 * Hub (Bridge) side. Listens on 127.0.0.1:<port>. Each connection must send
 * {type:'hello', secret, ...} within HELLO_TIMEOUT_MS or is destroyed.
 *
 * Bidirectional heartbeat: the hub pings authenticated connections every
 * intervalMs, the client answers pong; lastSeen updates on ANY valid traffic,
 * and a connection whose peer has been silent for timeoutMs is destroyed
 * (zombie cleanup). `listenOrFatal` enforces a STABLE configured port: if it
 * is occupied the startup FAILS (never a silent random port, which would
 * strand already-running channel clients on the old endpoint).
 */
function createIpcServer({ port = 0, secret, logInfo = () => {}, logWarn = () => {}, heartbeatIntervalMs = HEARTBEAT_INTERVAL_DEFAULT_MS, heartbeatTimeoutMs = HEARTBEAT_TIMEOUT_DEFAULT_MS }) {
  // FIX (port ownership): the port is bound at CONSTRUCTION and every listen
  // path uses it. Port 0 (ephemeral) is allowed ONLY for tests; production
  // passes the configured stable port here — the configured value can never
  // be lost between construction and listen (the bug that made
  // CLAUDE_CHANNEL_PORT non-authoritative).
  const HELLO_TIMEOUT_MS = 10_000;
  const conns = new Set();
  let heartbeatTimer = null;
  let connectionHandler = null; // set via onConnection() — hub integration point

  const server = net.createServer((raw) => {
    // Enforce loopback at the socket level too (defense in depth).
    const addr = raw.remoteAddress || '';
    if (!/^(127\.|::1|::ffff:127\.)/.test(addr)) {
      logWarn(`ipc: rejected non-loopback connection from ${addr}`);
      raw.destroy();
      return;
    }
    const conn = attachFraming(raw, {
      onError: (err) => logWarn(`ipc client error ${addr}: ${err.message}`),
    });
    conn.helloDone = false;
    conns.add(conn);

    const helloTimer = setTimeout(() => {
      if (!conn.helloDone) {
        logWarn('ipc: client did not authenticate in time');
        conn.destroy();
      }
    }, HELLO_TIMEOUT_MS);
    if (helloTimer.unref) helloTimer.unref();

    const offMsg = conn.on('message', (msg) => {
      if (!conn.helloDone) {
        if (!msg || msg.type !== 'hello' || typeof msg.secret !== 'string' || msg.secret.length < 16) {
          logWarn('ipc: invalid or missing hello/secret — connection rejected');
          conn.destroy();
          return;
        }
        // constant-time-ish compare
        const a = Buffer.from(msg.secret);
        const b = Buffer.from(secret);
        if (a.length !== b.length || !require('crypto').timingSafeEqual(a, b)) {
          logWarn('ipc: bad secret — connection rejected');
          conn.destroy();
          return;
        }
        conn.helloDone = true;
        clearTimeout(helloTimer);
        conn.send({ type: 'hello_ok', protocol: 1 });
        if (connectionHandler) connectionHandler({ conn, hello: msg });
        return;
      }
      if (msg.type === 'ping') {
        conn.send({ type: 'pong', t: msg.t });
      }
      // everything else is routed by the hub's onConnection handler
    });
    conn.on('close', () => {
      conns.delete(conn);
      clearTimeout(helloTimer);
      offMsg();
    });
  });

  server.on('error', (err) => logWarn(`ipc server error: ${err.message}`));

  function startHeartbeats() {
    const t = heartbeatTimeoutMs;
    heartbeatTimer = setInterval(() => {
      for (const c of conns) {
        if (!c.helloDone) continue;
        if (Date.now() - c.lastSeen > t) {
          logWarn('ipc: heartbeat timeout — dropping silent connection');
          c.destroy();
          continue;
        }
        c.send({ type: 'ping', t: Date.now() });
      }
    }, heartbeatIntervalMs);
    if (heartbeatTimer.unref) heartbeatTimer.unref();
  }

  return {
    /** Register the handler invoked after each successful hello. */
    onConnection(fn) {
      connectionHandler = fn;
    },
    /** The port the server ACTUALLY bound (== configured port; ephemeral only in tests). */
    get actualPort() {
      const a = server.address();
      return typeof a === 'object' && a ? a.port : null;
    },
    listen(cb) {
      server.listen(port, '127.0.0.1', () => {
        const actual = server.address();
        startHeartbeats();
        cb({
          port: typeof actual === 'object' ? actual.port : port,
          host: '127.0.0.1',
        });
      });
    },
    /**
     * Listen on the STABLE configured port. If it is occupied, invoke
     * onFatal(error) instead of silently picking another random port
     * (channel clients would keep reconnecting to the old dead endpoint).
     */
    listenOrFatal({ onFatal, onReady }) {
      server.once('error', (err) => {
        if (err && err.code === 'EADDRINUSE') {
          const fatal = new Error(`channel port 127.0.0.1:${port} is already in use — another bridge instance may be running. Not falling back to a random port: channel clients would keep reconnecting to a dead endpoint. Free the port or set CLAUDE_CHANNEL_PORT.`);
          fatal.code = 'EADDRINUSE';
          onFatal(fatal);
          try {
            server.close();
          } catch {
            /* ignore */
          }
          return;
        }
        logWarn(`ipc server error: ${err.message}`);
      });
      server.listen(port, '127.0.0.1', () => {
        const actual = server.address();
        startHeartbeats();
        if (onReady) {
          onReady({
            port: typeof actual === 'object' ? actual.port : port,
            host: '127.0.0.1',
          });
        }
      });
    },
    close() {
      if (heartbeatTimer) clearInterval(heartbeatTimer);
      for (const c of [...conns]) c.destroy();
      conns.clear();
      try {
        server.close();
      } catch {
        /* ignore */
      }
    },
    connections: () => [...conns],
  };
}

/**
 * Client (Channel server) side — THE shared production IPC client used by
 * lib/channel/claude-channel.js (previously that file kept its own raw
 * net.connect() that never answered ping frames, so idle sessions were
 * dropped by the hub's heartbeat timeout and reconnect-looped).
 *
 * Behavior: connects, sends hello with the secret, answers ping with pong,
 * reconnects with BOUNDED EXPONENTIAL backoff (2s → 4s → 8s → max 15s,
 * reset after a healthy authenticated connection) until close() is called.
 */
function createIpcClient({ port, secret, clientId, logInfo = () => {}, logWarn = () => {}, reconnectDelayMs = 2000, maxDelayMs = 15000, heartbeatIntervalMs = HEARTBEAT_INTERVAL_DEFAULT_MS } = {}) {
  let conn = null;
  let closedByUs = false;
  let attempts = 0;
  let reconnectTimer = null;
  let heartbeatTimer = null;
  let readyCb = null;
  let messageHandler = null;

  function clearHeartbeat() {
    if (heartbeatTimer) {
      clearInterval(heartbeatTimer);
      heartbeatTimer = null;
    }
  }

  function connectOnce() {
    const raw = net.connect(port, '127.0.0.1');
    const c = attachFraming(raw, { onError: (err) => logWarn(`ipc client: ${err.message}`) });

    c.on('close', () => {
      clearHeartbeat();
      conn = null;
      if (closedByUs) return;
      attempts += 1;
      // Bounded EXPONENTIAL backoff: 2s, 4s, 8s, 15s cap (fix: was linear,
      // and the docs claimed exponential while production used fixed 2s).
      const delay = Math.min(maxDelayMs, reconnectDelayMs * 2 ** (attempts - 1));
      logWarn(`ipc: disconnected from hub; retrying in ${Math.round(delay / 1000)}s (attempt ${attempts})`);
      reconnectTimer = setTimeout(connectOnce, delay);
      if (reconnectTimer.unref) reconnectTimer.unref();
    });

    c.on('message', (msg) => {
      // lastSeen is tracked inside attachFraming on any traffic.
      if (msg && msg.type === 'ping') {
        c.send({ type: 'pong', t: msg.t });
        return;
      }
      if (msg && msg.type === 'pong') return;
      if (msg && msg.type === 'hello_ok') {
        // Healthy authenticated session: reset reconnect backoff and fire
        // the start() callback exactly once per connection.
        attempts = 0;
        const cb = readyCb;
        readyCb = null;
        if (cb) cb({ conn: c });
        return;
      }
      if (messageHandler) messageHandler(msg, c);
    });

    raw.on('connect', () => {
      // attempts reset only after a HEALTHY authenticated session (hello_ok),
      // not on raw TCP connect — see the hello_ok handler below.
      c.send({ type: 'hello', secret, clientId, protocol: 1 });
      heartbeatTimer = setInterval(() => c.send({ type: 'ping', t: Date.now() }), heartbeatIntervalMs);
      if (heartbeatTimer.unref) heartbeatTimer.unref();
    });

    conn = c;
    return c;
  }

  return {
    start(onReady) {
      readyCb = onReady;
      // hello_ok readiness is intercepted in the message pump (connectOnce),
      // NOT via a self-referencing wrapper here (the previous wrapper called
      // itself — `messageHandler` was orig — blowing the stack on the first
      // hello_ok frame).
      connectOnce();
    },
    onMessage(fn) {
      messageHandler = fn;
    },
    send(obj) {
      return conn ? conn.send(obj) : false;
    },
    isConnected() {
      return !!conn && !conn.destroyed;
    },
    close() {
      closedByUs = true;
      clearHeartbeat();
      if (reconnectTimer) clearTimeout(reconnectTimer);
      if (conn) conn.close();
      conn = null;
    },
  };
}

module.exports = {
  createIpcServer,
  createIpcClient,
  attachFraming,
  validateHeartbeatConfig,
  MAX_FRAME_BYTES,
  HEARTBEAT_INTERVAL_DEFAULT_MS,
  HEARTBEAT_TIMEOUT_DEFAULT_MS,
  HEARTBEAT_BOUNDS,
};
